GaetanDuq/centsible

- app/controllers/transactions_controller.rb
- app/views/transactions/index.html.erb
did the logic behind it.. put in the skeleton
> done with available balance and total spent

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/devise/sessions/new.html.erb
- app/views/transactions/index.html.erb
- app/views/users/dashboard.html.erb
changed sign in page, dashboard balance, transactions index boxes
> changed sign in page, dashboard balance, transactions index boxes

- app/models/category.rb
- app/views/categories/index.html.erb
- app/views/transactions/index.html.erb
Added colors and also the checkbox style categories. Worked on piechart as welll....
> Color categories

- app/javascript/controllers/messages_controller.js
no visual changes but applied turbo stream  to window
> improved chatbot window

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/messages/index.html.erb
> changed chat color

- db/seeds.rb
removed income from seeds and added 6m of income
> removed income seeds

- app/assets/config/manifest.json.erb
> change screen

- app/views/shared/_footer_navbar.html.erb
swapped categories with ai chat
> changed chat with categories

- app/assets/stylesheets/components/_footer_navbar.scss
- app/views/layouts/application.html.erb
Reverted all changes I made for the PWA
> reverted my changes for PWA

- app/views/shared/_navbar.html.erb
> Icons menu

- db/seeds.rb
The seeds are MORE realistics and start January 1st of this year.
We will have 600 transactions created.
> seeds working

- app/controllers/categories_controller.rb
- app/controllers/concerns/range_filterable.rb
- app/controllers/transactions_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/models/transaction.rb
- app/views/transactions/index.html.erb
- app/views/users/_balance_box.html.erb
- app/views/users/dashboard.html.erb
> Fixed the balance boxes so it reflect the the filter we are on

- app/controllers/savings_controller.rb
> removed the Saving title from the description

- app/views/categories/budget.html.erb
- app/views/categories/index.html.erb
> done with linking budget

- app/controllers/messages_controller.rb
- app/javascript/controllers/messages_controller.js
- app/models/message.rb
- app/models/user.rb
- app/tools/categories_finder_tool.rb
- app/tools/categories_tool.rb
- app/tools/past_transaction_tool.rb
- app/tools/text_transaction_maker_tool.rb
- app/views/messages/index.html.erb
- app/views/partials/_message.html.erb
Refactored LLM code, now uses params to build transactions
> Llm transaction

- app/controllers/transactions_controller.rb
- app/models/transaction.rb
- app/views/partials/_form.html.erb
- app/views/users/dashboard.html.erb
field required popping up when a field is left blank
> field required errors

- app/views/categories/index.html.erb
added commas to amounts in categories
> added commas

- app/helpers/application_helper.rb
- app/views/transactions/index.html.erb
- app/views/users/_balance_box.html.erb
fixed the balance box and added visual cues
> visual cues

- app/controllers/chat_transactions_controller.rb
- app/controllers/messages_controller.rb
- app/views/partials/_confirm_bar.html.erb
> confirm button works

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_icon_for_ai.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_msg_img.scss
- app/javascript/controllers/speech_to_text_controller.js
- app/views/partials/_chat_form.html.erb
- app/views/partials/_message.html.erb
- config/application.rb
Done with the picture and everything
> Adding gallery option

- app/controllers/messages_controller.rb
> Limited chat history build method and view

- app/views/categories/budget.html.erb
- app/views/categories/index.html.erb
> category and saving styling

- app/views/categories/budget.html.erb
- app/views/categories/index.html.erb
- app/views/savings/index.html.erb
- app/views/transactions/index.html.erb
> added some icons to the headings and th buttons

- app/models/message.rb
- db/seeds.rb
The prompt gives us good answer when asking for advise
> Better prompt

- app/assets/stylesheets/components/_chat_messages.scss
- app/views/categories/budget.html.erb
- app/views/categories/index.html.erb
- app/views/savings/index.html.erb
- app/views/transactions/index.html.erb
- app/views/users/_balance_box.html.erb
- app/views/users/dashboard.html.erb
> Icons title

- app/controllers/categories_controller.rb
- app/controllers/savings_controller.rb
- app/views/savings/index.html.erb
added the balance box in piggy bank
> added box in piggy

- app/views/shared/_navbar.html.erb
> added dashboard to the menu

- app/views/savings/index.html.erb
> Saving page looking better

- app/views/layouts/application.html.erb
- public/manifest.webmanifest
> tweaked pwa settings

- app/assets/stylesheets/application.scss
- app/views/categories/index.html.erb
- app/views/messages/index.html.erb
- app/views/savings/index.html.erb
- app/views/shared/_footer_navbar.html.erb
- app/views/shared/_navbar.html.erb
- app/views/transactions/index.html.erb
- app/views/users/dashboard.html.erb
Navbars don't slide when scrolled
> Navbar position fixed
